[unix_http_server]
 file=/var/www/html/supervisor.sock
 chown=www-data

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
user=www-data
serverurl=unix:///var/www/html/supervisor.sock

[supervisord]
pidfile=/var/www/html/supervisord.pid
logfile=/var/www/html/storage/logs/supervisord.log
loglevel=error
nodaemon=true
chown=www-data

[program:laravel-swoole]
command=/usr/local/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=swoole --port=8000
autostart=true
autorestart=true
startretries=5
numprocs=1
startsecs=0
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/var/www/html/storage/logs/swoole.log
user=www-data

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
startretries=5
numprocs=1
startsecs=0
user=www-data
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/var/www/html/storage/logs/error.log
stdout_logfile=/var/www/html/storage/logs/access.log
priority=1

[program:laravel-queue]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /var/www/html/artisan queue:work --sleep=3 --tries=3 --delay=30 --timeout=300 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker.log
stopwaitsecs=3600
user=www-data
priority=2

[program:laravel-scheduler]
process_name=%(program_name)s_%(process_num)02d
command=/bin/sh -c "while sleep 60; do /usr/local/bin/php /var/www/html/artisan schedule:run; done"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/schedule.log
stopwaitsecs=3600
user=www-data
priority=3
